# Generated by Django 5.0.1 on 2024-02-01 20:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Differente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(2024, 2, 1, 22, 36, 19, 650122)
                    ),
                ),
                ("lumicash", models.IntegerField(default=0)),
                ("lid", models.IntegerField(default=0)),
                ("mpesa", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Lid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(default="xddf", max_length=10)),
                ("solde", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15)),
                ("account", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PorteFeuille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_username",
                    models.CharField(
                        default="Noe", max_length=15, verbose_name="to be deprecated"
                    ),
                ),
                ("uid", models.CharField(default="xddf", max_length=10)),
                ("lumicash", models.IntegerField(default=0)),
                ("lid", models.IntegerField(default=0)),
                ("mpesa", models.IntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.IntegerField(default=0)),
                ("amount", models.IntegerField(default=0)),
                ("code_transaction", models.CharField(default="xdf", max_length=15)),
                (
                    "date_action",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 2, 1, 22, 36, 19, 648844)
                    ),
                ),
                ("anything", models.IntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Requeste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_to_send", models.IntegerField(default=0)),
                ("receiver_number", models.IntegerField(default=0)),
                ("amount_to_deb", models.IntegerField(default=0)),
                (
                    "state_progress",
                    models.IntegerField(
                        choices=[(1, "Pending"), (2, "Done")], default=1
                    ),
                ),
                (
                    "pay_method",
                    models.IntegerField(
                        choices=[(1, "LUMICASH"), (2, "PAYPAL"), (3, "eNOTI")],
                        default=1,
                    ),
                ),
                ("user_username", models.CharField(max_length=15)),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 2, 1, 22, 36, 19, 647652)
                    ),
                ),
                (
                    "date_approved",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 2, 1, 22, 36, 19, 647690)
                    ),
                ),
                (
                    "link_to_activate",
                    models.URLField(default="http://127.0.0.1:8000/jov/api/users//"),
                ),
                ("approved_by", models.CharField(default="None", max_length=15)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
