# Generated by Django 5.0.1 on 2024-02-02 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_remove_portefeuille_uid_alter_differente_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="differente",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 2, 2, 10, 15, 6, 242194)
            ),
        ),
        migrations.AlterField(
            model_name="portefeuille",
            name="lid",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 2, 10, 15, 6, 241480)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 2, 10, 15, 6, 240283)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 2, 10, 15, 6, 240243)
            ),
        ),
    ]
