# Generated by Django 5.0.1 on 2024-02-02 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_alter_differente_date_alter_portefeuille_lid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="differente",
            name="name",
            field=models.CharField(
                default="Vente", max_length=10, verbose_name="Vente ou Achat"
            ),
        ),
        migrations.AlterField(
            model_name="differente",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 2, 2, 10, 23, 41, 34235)
            ),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 2, 10, 23, 41, 33493)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 2, 10, 23, 41, 32428)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 2, 10, 23, 41, 32373)
            ),
        ),
    ]
