# Generated by Django 5.0.1 on 2024-03-16 14:41

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0008_alter_differente_date_alter_recharge_date_action_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="differente",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 16, 16, 41, 30, 952335)
            ),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 16, 16, 41, 30, 951073)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 16, 16, 41, 30, 949988)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 16, 16, 41, 30, 949952)
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 16, 16, 41, 30, 953406)
            ),
        ),
        migrations.CreateModel(
            name="DepotPreuve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="null", max_length=10)),
                ("deposant", models.CharField(default="nulldeposant", max_length=25)),
                ("numero", models.CharField(default="numerovide", max_length=25)),
                (
                    "montant",
                    models.IntegerField(
                        default=0, help_text="Le montant que vous deposez"
                    ),
                ),
                ("bordereau", models.ImageField(upload_to="depots/")),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 3, 16, 16, 41, 30, 955177)
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
