# Generated by Django 5.0.1 on 2024-03-21 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0014_alter_depotpreuve_date_alter_differente_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentsMade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency", models.CharField(default="null", max_length=10)),
                (
                    "capital",
                    models.IntegerField(
                        default=0,
                        help_text="Le montant que vous voulez                                   investir",
                    ),
                ),
                (
                    "taux",
                    models.FloatField(default=0, help_text="Le taux d'interet annuel"),
                ),
                (
                    "duree",
                    models.IntegerField(
                        default=0,
                        help_text="Le duree que vous devez                                   attendre",
                    ),
                ),
                (
                    "result",
                    models.IntegerField(
                        default=0,
                        help_text="Le montant que vous aurez                                   investir",
                    ),
                ),
                (
                    "date_submitted",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024,
                            3,
                            21,
                            15,
                            46,
                            47,
                            516335,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 21, 15, 46, 47, 514512, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="differente",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 21, 17, 46, 47, 511660)
            ),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 21, 17, 46, 47, 510539)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 21, 17, 46, 47, 509374)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 21, 17, 46, 47, 509335)
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 21, 15, 46, 47, 515554, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 21, 15, 46, 47, 515491, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="montant",
            field=models.IntegerField(
                default=0, help_text="Le montant que vous Retirer"
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 21, 17, 46, 47, 512420)
            ),
        ),
    ]
