# Generated by Django 5.0.1 on 2024-03-22 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app1",
            "0022_rename_link_to_activate_investmentsmade_link_to_approve_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentsmade",
            name="owner",
            field=models.CharField(default="null", max_length=10),
        ),
        migrations.AddField(
            model_name="investmentsmade",
            name="who_approved",
            field=models.CharField(default="null", max_length=10),
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 22, 8, 52, 5, 164353, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="differente",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 22, 10, 52, 5, 163477)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 22, 10, 52, 5, 164918)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 22, 10, 52, 5, 164907)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="link_to_approve",
            field=models.URLField(
                default="http://127.0.0.1:8002/jov/api/", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 22, 10, 52, 5, 163123)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 22, 10, 52, 5, 162740)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 22, 10, 52, 5, 162725)
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 22, 8, 52, 5, 164633, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 22, 8, 52, 5, 164621, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 22, 10, 52, 5, 163739)
            ),
        ),
    ]
