# Generated by Django 5.0.1 on 2024-03-25 09:43

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0024_remove_depotpreuve_date_depotpreuve_approved_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="depotpreuve",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 25, 11, 43, 1, 528014)
            ),
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 25, 11, 43, 1, 527989)
            ),
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="link_to_approve",
            field=models.URLField(
                default="http://localhost:8002/jov/api/depot/4/approveDepot/",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="differente",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 25, 11, 43, 1, 527079)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 25, 11, 43, 1, 528649)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 25, 11, 43, 1, 528639)
            ),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 25, 11, 43, 1, 526690)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 25, 11, 43, 1, 526275)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 25, 11, 43, 1, 526258)
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 25, 9, 43, 1, 528349, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 25, 9, 43, 1, 528334, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 25, 11, 43, 1, 527373)
            ),
        ),
        migrations.CreateModel(
            name="Solde",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "usdt",
                    models.FloatField(default=0, help_text="Le solde actuel en usdt"),
                ),
                (
                    "usd",
                    models.FloatField(
                        default=0, help_text="Le solde actuel en US Dollar"
                    ),
                ),
                (
                    "bif",
                    models.FloatField(default=0, help_text="Le solde actuel en FBU"),
                ),
                (
                    "rwf",
                    models.FloatField(default=0, help_text="Le solde actuel en Frw"),
                ),
                (
                    "kes",
                    models.FloatField(
                        default=0, help_text="Le solde actuel en ShillingKenya"
                    ),
                ),
                (
                    "ugx",
                    models.FloatField(
                        default=0, help_text="Le solde actuel en Ugshilling"
                    ),
                ),
                (
                    "tsh",
                    models.FloatField(
                        default=0, help_text="Le solde actuel en ShillingTanzania"
                    ),
                ),
                (
                    "zmw",
                    models.FloatField(default=0, help_text="Le solde actuel en Kwacha"),
                ),
                (
                    "eur",
                    models.FloatField(default=0, help_text="Le solde actuel en Euro"),
                ),
                (
                    "trx",
                    models.FloatField(default=0, help_text="Le solde actuel en TRX"),
                ),
                (
                    "lid",
                    models.FloatField(
                        default=0, help_text="Le solde actuel en Lit Dinar"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
