# Generated by Django 5.0.1 on 2024-03-26 13:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0029_alter_depotpreuve_date_approved_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="depotpreuve",
            name="approved",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 26, 15, 25, 2, 732471)
            ),
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 26, 15, 25, 2, 732404)
            ),
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="link_to_approve",
            field=models.URLField(
                default="http://localhost:8002/jov/api/depot/4/approveDepot/",
                editable=False,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="differente",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 26, 15, 25, 2, 729813)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="approved",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 26, 15, 25, 2, 734378)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 26, 15, 25, 2, 734350)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="link_to_approve",
            field=models.URLField(
                default="http://127.0.0.1:8002/jov/api/", editable=False, max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="operationstore",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 26, 15, 25, 2, 736547)
            ),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 26, 15, 25, 2, 728524)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 26, 15, 25, 2, 727320)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 3, 26, 15, 25, 2, 727280)
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 26, 13, 25, 2, 733458, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 26, 13, 25, 2, 733421, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="solde",
            name="owner",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 3, 26, 15, 25, 2, 730646)
            ),
        ),
    ]
