# Generated by Django 5.0.1 on 2024-04-02 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0032_operationstore_charge_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="retraitlives",
            old_name="benefitor",
            new_name="destination",
        ),
        migrations.AddField(
            model_name="retraitlives",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="retraitlives",
            name="link_to_approve",
            field=models.URLField(
                default="http://localhost:8002/jov/api/depot/4/approveDepot/",
                editable=False,
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="retraitlives",
            name="owner",
            field=models.CharField(default="null", max_length=10),
        ),
        migrations.AddField(
            model_name="retraitlives",
            name="who_approved",
            field=models.CharField(default="null", max_length=10),
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 2, 22, 22, 19, 24719)
            ),
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 2, 22, 22, 19, 24649)
            ),
        ),
        migrations.AlterField(
            model_name="differente",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 2, 22, 22, 19, 22200)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 2, 22, 22, 19, 26821)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 2, 22, 22, 19, 26639)
            ),
        ),
        migrations.AlterField(
            model_name="operationstore",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 2, 22, 22, 19, 28940)
            ),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 2, 22, 22, 19, 21176)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 2, 22, 22, 19, 20071)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 2, 22, 22, 19, 20032)
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 2, 20, 22, 19, 25659, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 2, 20, 22, 19, 25623, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 2, 22, 22, 19, 22970)
            ),
        ),
    ]
