# Generated by Django 5.0.1 on 2024-04-03 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0038_alter_depotpreuve_date_approved_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionForWithdraw",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bif", models.CharField(default="null", max_length=30)),
                ("eur", models.CharField(default="null", max_length=15)),
                ("kes", models.CharField(default="null", max_length=20)),
                ("rwf", models.CharField(default="null", max_length=25)),
                ("trx", models.CharField(default="null", max_length=15)),
                ("tsh", models.CharField(default="null", max_length=30)),
                ("ugx", models.CharField(default="null", max_length=30)),
                ("usd", models.CharField(default="null", max_length=15)),
                ("usdt", models.CharField(default="null", max_length=15)),
                ("zmw", models.CharField(default="null", max_length=30)),
                (
                    "date_approved",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 4, 3, 12, 7, 25, 236284)
                    ),
                ),
                ("who_approved", models.CharField(default="null", max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 12, 7, 25, 230490)
            ),
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 12, 7, 25, 230414)
            ),
        ),
        migrations.AlterField(
            model_name="differente",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 3, 12, 7, 25, 227715)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 12, 7, 25, 233425)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 12, 7, 25, 233395)
            ),
        ),
        migrations.AlterField(
            model_name="operationstore",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 12, 7, 25, 235405)
            ),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 12, 7, 25, 226720)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 12, 7, 25, 225649)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 12, 7, 25, 225614)
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 3, 10, 7, 25, 231742, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 3, 10, 7, 25, 231669, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 3, 12, 7, 25, 228455)
            ),
        ),
    ]
