# Generated by Django 5.0.1 on 2024-04-03 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0039_commissionforwithdraw_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommissionForWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bif", models.CharField(default="null", max_length=30)),
                ("eur", models.CharField(default="null", max_length=15)),
                ("kes", models.CharField(default="null", max_length=20)),
                ("rwf", models.CharField(default="null", max_length=25)),
                ("trx", models.CharField(default="null", max_length=15)),
                ("tsh", models.CharField(default="null", max_length=30)),
                ("ugx", models.CharField(default="null", max_length=30)),
                ("usd", models.CharField(default="null", max_length=15)),
                ("usdt", models.CharField(default="null", max_length=15)),
                ("zmw", models.CharField(default="null", max_length=30)),
                (
                    "date_approved",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 4, 3, 12, 9, 24, 149486)
                    ),
                ),
                ("who_approved", models.CharField(default="null", max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name="CommissionForWithdraw",
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 12, 9, 24, 147723)
            ),
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 12, 9, 24, 147698)
            ),
        ),
        migrations.AlterField(
            model_name="differente",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 3, 12, 9, 24, 146784)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 12, 9, 24, 148453)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 12, 9, 24, 148441)
            ),
        ),
        migrations.AlterField(
            model_name="operationstore",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 12, 9, 24, 149175)
            ),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 12, 9, 24, 146429)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 12, 9, 24, 146041)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 12, 9, 24, 146027)
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 3, 10, 9, 24, 148051, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 3, 10, 9, 24, 148037, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 3, 12, 9, 24, 147076)
            ),
        ),
    ]
