# Generated by Django 5.0.1 on 2024-04-03 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0040_commissionforwithdrawal_delete_commissionforwithdraw_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionforwithdrawal",
            name="bif",
            field=models.CharField(default="5_000/1_000_000", max_length=30),
        ),
        migrations.AlterField(
            model_name="commissionforwithdrawal",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 14, 7, 29, 691531)
            ),
        ),
        migrations.AlterField(
            model_name="commissionforwithdrawal",
            name="eur",
            field=models.CharField(default="1/1_000", max_length=15),
        ),
        migrations.AlterField(
            model_name="commissionforwithdrawal",
            name="kes",
            field=models.CharField(default="50/1_000", max_length=20),
        ),
        migrations.AlterField(
            model_name="commissionforwithdrawal",
            name="rwf",
            field=models.CharField(default="3_000/1_000_000", max_length=25),
        ),
        migrations.AlterField(
            model_name="commissionforwithdrawal",
            name="trx",
            field=models.CharField(default="1/1_000", max_length=15),
        ),
        migrations.AlterField(
            model_name="commissionforwithdrawal",
            name="tsh",
            field=models.CharField(default="5_000/1_000_000", max_length=30),
        ),
        migrations.AlterField(
            model_name="commissionforwithdrawal",
            name="ugx",
            field=models.CharField(default="8_000/1_000_000", max_length=30),
        ),
        migrations.AlterField(
            model_name="commissionforwithdrawal",
            name="usd",
            field=models.CharField(default="1/1_000", max_length=15),
        ),
        migrations.AlterField(
            model_name="commissionforwithdrawal",
            name="usdt",
            field=models.CharField(default="1/1_000", max_length=15),
        ),
        migrations.AlterField(
            model_name="commissionforwithdrawal",
            name="zmw",
            field=models.CharField(default="5_000/1_000_000", max_length=30),
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 14, 7, 29, 686446)
            ),
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 14, 7, 29, 686367)
            ),
        ),
        migrations.AlterField(
            model_name="differente",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 3, 14, 7, 29, 682884)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 14, 7, 29, 688702)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 14, 7, 29, 688671)
            ),
        ),
        migrations.AlterField(
            model_name="operationstore",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 14, 7, 29, 690663)
            ),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 14, 7, 29, 681735)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 14, 7, 29, 680162)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 3, 14, 7, 29, 680124)
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 3, 12, 7, 29, 687472, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 3, 12, 7, 29, 687435, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 3, 14, 7, 29, 683939)
            ),
        ),
    ]
