# Generated by Django 5.0.1 on 2024-04-06 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0051_alter_commissionforwithdrawal_date_approved_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoolUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(default="null", max_length=8)),
                ("username", models.CharField(default="null", max_length=15)),
                ("password", models.CharField(default="null", max_length=25)),
                ("email", models.CharField(default="null", max_length=25)),
                ("phone", models.CharField(default="null", max_length=15)),
                (
                    "date_submitted",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 4, 6, 10, 26, 28, 123385)
                    ),
                ),
                (
                    "date_approved",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 4, 6, 10, 26, 28, 123411)
                    ),
                ),
                ("activated", models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="commissionforwithdrawal",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 26, 28, 122617)
            ),
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 26, 28, 116846)
            ),
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 26, 28, 116778)
            ),
        ),
        migrations.AlterField(
            model_name="differente",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 6, 10, 26, 28, 114216)
            ),
        ),
        migrations.AlterField(
            model_name="interestrateforinvestment",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 26, 28, 119835)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 26, 28, 118916)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_deadline",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 6, 10, 26, 28, 118938)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 26, 28, 118889)
            ),
        ),
        migrations.AlterField(
            model_name="operationstore",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 26, 28, 121546)
            ),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 26, 28, 113409)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 26, 28, 112268)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 26, 28, 112228)
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 6, 8, 26, 28, 117966, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 6, 8, 26, 28, 117930, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 6, 10, 26, 28, 114987)
            ),
        ),
    ]
