# Generated by Django 5.0.1 on 2024-04-06 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0052_pooluser_alter_commissionforwithdrawal_date_approved_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commissionforwithdrawal",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 45, 44, 679119)
            ),
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 45, 44, 673256)
            ),
        ),
        migrations.AlterField(
            model_name="depotpreuve",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 45, 44, 673176)
            ),
        ),
        migrations.AlterField(
            model_name="differente",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 6, 10, 45, 44, 670816)
            ),
        ),
        migrations.AlterField(
            model_name="interestrateforinvestment",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 45, 44, 676367)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 45, 44, 675395)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_deadline",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 6, 10, 45, 44, 675429)
            ),
        ),
        migrations.AlterField(
            model_name="investmentsmade",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 45, 44, 675365)
            ),
        ),
        migrations.AlterField(
            model_name="operationstore",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 45, 44, 678198)
            ),
        ),
        migrations.AlterField(
            model_name="pooluser",
            name="code",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="pooluser",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 45, 44, 680090)
            ),
        ),
        migrations.AlterField(
            model_name="pooluser",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 45, 44, 680062)
            ),
        ),
        migrations.AlterField(
            model_name="pooluser",
            name="email",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="pooluser",
            name="password",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="pooluser",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="pooluser",
            name="username",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 45, 44, 669814)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 45, 44, 668669)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 6, 10, 45, 44, 668632)
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 6, 8, 45, 44, 674227, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="retraitlives",
            name="date_submitted",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 4, 6, 8, 45, 44, 674189, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 4, 6, 10, 45, 44, 671559)
            ),
        ),
    ]
