# Generated by Django 5.0.1 on 2024-01-31 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_alter_recharge_date_action_and_more"),
    ]

    operations = []
