# Generated by Django 5.0.1 on 2024-01-31 13:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0016_alter_recharge_date_action_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(default="xddf", max_length=10)),
                ("solde", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 31, 15, 17, 37, 559915)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 31, 15, 17, 37, 558849)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 31, 15, 17, 37, 558812)
            ),
        ),
        migrations.AlterField(
            model_name="portefeuille",
            name="lid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.lid"
            ),
        ),
    ]
