# Generated by Django 5.0.1 on 2024-02-01 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0019_portefeuille_amount_alter_recharge_date_action_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portefeuille",
            old_name="amount",
            new_name="mpesa",
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 1, 9, 19, 31, 447900)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 1, 9, 19, 31, 446730)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 2, 1, 9, 19, 31, 446689)
            ),
        ),
    ]
