# Generated by Django 5.0.1 on 2024-01-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requestes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_t_cred", models.IntegerField(default=0)),
                ("amount_to_deb", models.IntegerField(default=0)),
                (
                    "state_progress",
                    models.IntegerField(
                        choices=[(1, "Pending"), (2, "In Work"), (3, "Completed")],
                        default=(1, "Pending"),
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="account",
            field=models.IntegerField(default=0),
        ),
    ]
