# Generated by Django 5.0.1 on 2024-01-16 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_requestes_person_account"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PorteFeuille",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("user_username", models.CharField(max_length=15)),
                ("lumicash", models.IntegerField()),
                ("paypal", models.IntegerField()),
                ("enoti", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Requeste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_t_cred", models.IntegerField(default=0)),
                ("amount_to_deb", models.IntegerField(default=0)),
                (
                    "state_progress",
                    models.IntegerField(
                        choices=[(1, "Pending"), (2, "In Work"), (3, "Completed")],
                        default=(1, "Pending"),
                    ),
                ),
                (
                    "pay_method",
                    models.IntegerField(
                        choices=[(1, "LUMICASH"), (2, "PAYPAL"), (3, "eNOTI")],
                        default=1,
                    ),
                ),
                ("user_username", models.CharField(max_length=15)),
                ("date_created", models.DateTimeField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Requestes",
        ),
    ]
