# Generated by Django 5.0.1 on 2024-01-16 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0003_portefeuille_requeste_delete_requestes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2024, 1, 16, 12, 28, 0, 421606)
            ),
        ),
    ]
