# Generated by Django 5.0.1 on 2024-01-16 12:38

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0004_alter_requeste_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name=datetime.datetime(
                    2024, 1, 16, 12, 38, 34, 449611, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                verbose_name=datetime.datetime(2024, 1, 16, 12, 38, 34, 449588)
            ),
        ),
    ]
