# Generated by Django 5.0.1 on 2024-01-18 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0012_alter_requeste_date_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requeste",
            name="link_to_activate",
            field=models.URLField(default="http://127.0.0.1:8000/jov/api/users//"),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 18, 15, 27, 32, 267467)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 18, 15, 27, 32, 267452)
            ),
        ),
    ]
