# Generated by Django 5.0.1 on 2024-01-20 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0013_requeste_link_to_activate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requeste",
            name="approved_by",
            field=models.CharField(default="None", max_length=15),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 20, 5, 54, 49, 53414)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 20, 5, 54, 49, 53374)
            ),
        ),
    ]
