# Generated by Django 5.0.1 on 2024-01-20 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0015_alter_requeste_date_approved_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="portefeuille",
            old_name="user_id",
            new_name="owner_id",
        ),
        migrations.RemoveField(
            model_name="portefeuille",
            name="user_username",
        ),
        migrations.AddField(
            model_name="portefeuille",
            name="owner_username",
            field=models.CharField(default="Noe", max_length=15),
        ),
        migrations.AlterField(
            model_name="portefeuille",
            name="enoti",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="portefeuille",
            name="lumicash",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="portefeuille",
            name="paypal",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 20, 6, 34, 36, 263604)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 20, 6, 34, 36, 263567)
            ),
        ),
    ]
