# Generated by Django 5.0.1 on 2024-01-20 04:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0016_rename_user_id_portefeuille_owner_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 20, 6, 45, 54, 409605)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 20, 6, 45, 54, 409566)
            ),
        ),
    ]
