# Generated by Django 5.0.1 on 2024-01-21 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0018_remove_portefeuille_owner_id_portefeuille_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="requeste",
            old_name="amount_t_cred",
            new_name="amount_to_send",
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 21, 8, 29, 16, 836383)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 21, 8, 29, 16, 836342)
            ),
        ),
    ]
