# Generated by Django 5.0.1 on 2024-01-21 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0019_rename_amount_t_cred_requeste_amount_to_send_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requeste",
            name="receiver_number",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 21, 8, 31, 29, 190995)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 21, 8, 31, 29, 190979)
            ),
        ),
    ]
