# Generated by Django 5.0.1 on 2024-01-27 05:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0034_alter_recharge_date_action_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="BIF", max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name="Enoti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solde", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Lumicash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solde", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="USD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solde", models.IntegerField(default=0)),
                ("paypal", models.IntegerField(default=0)),
                ("usdt", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 27, 7, 15, 10, 386220)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 27, 7, 15, 10, 385027)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 27, 7, 15, 10, 384990)
            ),
        ),
        migrations.CreateModel(
            name="BIF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solde", models.IntegerField(default=0)),
                (
                    "enoti",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.enoti"
                    ),
                ),
                (
                    "lumicash",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.lumicash"
                    ),
                ),
            ],
        ),
    ]
