# Generated by Django 5.0.1 on 2024-01-27 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0035_currency_enoti_lumicash_usd_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayMethods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Lumicash", max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name="bif",
            name="enoti",
        ),
        migrations.RemoveField(
            model_name="bif",
            name="lumicash",
        ),
        migrations.DeleteModel(
            name="USD",
        ),
        migrations.AddField(
            model_name="currency",
            name="solde",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 27, 12, 10, 53, 821577)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 27, 12, 10, 53, 820361)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 27, 12, 10, 53, 820321)
            ),
        ),
        migrations.AddField(
            model_name="currency",
            name="paymethods",
            field=models.ManyToManyField(to="app1.paymethods"),
        ),
        migrations.DeleteModel(
            name="Enoti",
        ),
        migrations.DeleteModel(
            name="BIF",
        ),
        migrations.DeleteModel(
            name="Lumicash",
        ),
    ]
