# Generated by Django 5.0.1 on 2024-01-27 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0036_paymethods_remove_bif_enoti_remove_bif_lumicash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portefeuille",
            name="currency",
            field=models.ManyToManyField(to="app1.currency"),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 27, 12, 27, 55, 608756)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 27, 12, 27, 55, 607648)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 27, 12, 27, 55, 607610)
            ),
        ),
    ]
