# Generated by Django 5.0.1 on 2024-01-29 13:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0040_alter_recharge_date_action_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="BiF",
        ),
        migrations.RemoveField(
            model_name="currency",
            name="paymethods",
        ),
        migrations.RemoveField(
            model_name="portefeuille",
            name="currency",
        ),
        migrations.DeleteModel(
            name="USD",
        ),
        migrations.RemoveField(
            model_name="portefeuille",
            name="enoti",
        ),
        migrations.RemoveField(
            model_name="portefeuille",
            name="paypal",
        ),
        migrations.AddField(
            model_name="portefeuille",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="portefeuille",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="recharge",
            name="date_action",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 29, 15, 23, 14, 325392)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_approved",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 29, 15, 23, 14, 324933)
            ),
        ),
        migrations.AlterField(
            model_name="requeste",
            name="date_created",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 29, 15, 23, 14, 324916)
            ),
        ),
        migrations.DeleteModel(
            name="PayMethods",
        ),
        migrations.DeleteModel(
            name="Currency",
        ),
    ]
